import os
import hashlib
import platform
import uuid
import math
import cryptography
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
import rsa
import logging
import pickle
import ctypes  # For memory ops

#
# General tools
#________

def generate128Bits():
    return os.urandom(16)

def generate256Bits():
    return os.urandom(32)

def generate512Bits():
    return os.urandom(64)

#
# RSA Tools and tricks
#________

def generateRSAKeys():
    """Generates Br Standard RSA keys with 4096 bits. The key length is generally considered safe though may be changed in the future.

    Returns:
        tuple (publicKey, privateKey): Specified 4096 bit key pair.
    """
    publicKey, privateKey = rsa.newkeys(4096)
    return publicKey, privateKey

#
# AES Tools and tricks
#________

def deriveKeyFromBytes(salt:bytes, keyBytes:bytes):
    """This method uses bytes (similar to a password) to derive an AES encryption key.

    Args:
        salt (Bytes): Random bytes used in the encryption of AES data.

    Returns:
        Bytes: The derived AES key in Bytes.
    """
    
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=100000,
        backend=default_backend()
    )
    encKey = kdf.derive(keyBytes)
    return encKey

def encryptWithAES(dataObj: bytes, key:bytes, salt:bytes, iv:bytes = None):
    """This method uses AES to encrypt data using the provided salt, and iv.

    Args:
        dataObj (Bytes): Bytes to be encrypted.
        key (bytes): AES Encryption key.
        salt (Bytes): Unique 16 bytes used for encryption.
        iv (Bytes):Unique 16 bytes used for encryption.

    Returns:
        tuple: (iv, encrypted_data) Initilization Vector and the data. Store the IV since it is needed for decryption.
    """
    if iv is None:
        iv = os.urandom(16)
    cipher = Cipher(algorithms.AES(key), modes.CFB(iv), backend=default_backend())
    encryptor = cipher.encryptor()
    encrypted_data = encryptor.update(dataObj) + encryptor.finalize()
    return iv, encrypted_data  # NOTE: Added iv return if not provided, for consistency with encryptLocalData.

def decryptWithAES(dataObj: bytes, keyBytes: bytes, iv: bytes, salt: bytes):
    
    cipher = Cipher(algorithms.AES(keyBytes), modes.CFB(iv), backend=default_backend())
    decryptor = cipher.decryptor()
    decrypted_data = decryptor.update(dataObj) + decryptor.finalize()
    return decrypted_data

# Additional security utils from notrustvars
def getNewSalt():
    """Generates a 16-Byte (128-bit) random salt used in AES encryption.

    Returns:
        bytes: Salt generated by the system's OS.
    """
    return os.urandom(16)  # 128-bit salt

def __getMachineIdentity__():
    """Generates a unique identifier for the current machine using a combination of hardware and system factors.
    This is used to verify the system's identity and derive a decryption key.
    
    Enhancements: Includes additional factors like architecture, processor, OS release, and version for better uniqueness and robustness against spoofing.
    
    Returns:
        tuple: (identifier, idHash) String identifying the current machine and a SHA hash of that identifier.
    """
    # Collect multiple stable identifiers to increase uniqueness and resistance to changes
    identifiers = [
        str(uuid.getnode()),          # MAC address (network hardware)
        platform.system(),            # OS type (e.g., 'Windows', 'Linux')
        platform.node(),              # Hostname
        platform.machine(),           # Machine architecture (e.g., 'x86_64')
        platform.processor(),         # Processor name (e.g., 'Intel64 Family 6 Model 158 Stepping 13')
        platform.release(),           # OS release (e.g., kernel version)
        platform.version(),           # OS version (detailed release info)
    ]
    
    # Join them into a single string for hashing
    identifier = '-'.join(identifiers)
    idHash = hashlib.sha256(identifier.encode("utf-8")).hexdigest()
    return (identifier, idHash)

def derive_key(salt):
    """This method uses the system's identity to derive an AES encryption key.

    Args:
        salt (Bytes): Random bytes used in the encryption of AES data.

    Returns:
        Bytes: The derived AES key in Bytes.
    """
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=100000,
        backend=default_backend()
    )
    identifier, idHash = __getMachineIdentity__()
    machineDerivedKey = kdf.derive(identifier.encode("utf-8"))
    return machineDerivedKey

def getMachineSHA256():
    identifier, idHash = __getMachineIdentity__()
    return idHash

def encryptLocalData(dataObj, salt):
    """Uses AES to encrypt data using the System's unique key.

    Args:
        dataObj (Bytes): Bytes to be encrypted.
        salt (Bytes): Unique 16 bytes used for encryption.

    Returns:
        tuple: (iv, encrypted_data) Initilization Vector and the data. Store the IV since it is needed for decryption.
    """
    iv = os.urandom(16)
    machineKey = derive_key(salt)
    cipher = Cipher(algorithms.AES(machineKey), modes.CFB(iv), backend=default_backend())
    encryptor = cipher.encryptor()
    encrypted_data = encryptor.update(dataObj) + encryptor.finalize()
    return iv, encrypted_data

def decryptLocalData(dataObj, initVector, salt):
    """Uses AES to decrypt data using the original initilization vector and salt.

    Args:
        dataObj (bytes): AES encrypted data
        initVector (bytes): Unique 16 bytes used for encryption.
        salt (bytes): Unique 16 bytes used for encryption.

    Returns:
        bytes: Decrypted bytes
    """
    machineDerivedKey = derive_key(salt)
    cipher = Cipher(algorithms.AES(machineDerivedKey), modes.CFB(initVector), backend=default_backend())
    decryptor = cipher.decryptor()
    decrypted_data = decryptor.update(dataObj) + decryptor.finalize()
    machineDerivedKey = destroyData(machineDerivedKey)  # NOTE: Self-cleanup for security.
    return decrypted_data

def secure_zero_memory(data):
    """Overwrite the memory of the given data with Zeros."""
    size = len(data)
    ctypes.memset(id(data) + ctypes.sizeof(ctypes.c_size_t) * 2, 0, size)
    # NOTE: This is a best-effort in Python; consider using secrets module for secure bytes in future.

def destroyData(referenceToData, varName:str=None):
    """Method overwrites your variable with zeros in memory to protect against memory attacks.

    Args:
        referenceToData (Any): Any Python object
        varName (Str, None): Name of variable used for debug purposes. Otherwise non-specific. Defaults to None.

    Returns:
        Bytes: Bytes to overwrite the current variable in memory.
    """
    if varName is not None:
        logging.debug(f'Destroying reference to "{varName}" in memory with zeros...')
    else:
        logging.debug(f'Destroying reference to a variable in memory with zeros...')

    if isinstance(referenceToData, bytes):
        return b'\x00' * len(referenceToData)
    elif isinstance(referenceToData, rsa.PrivateKey):
        secure_zero_memory(referenceToData.d)
        secure_zero_memory(referenceToData.p)
        secure_zero_memory(referenceToData.q)
        secure_zero_memory(referenceToData.exp1)
        secure_zero_memory(referenceToData.exp2)
        secure_zero_memory(referenceToData.coef)
        return None
    # NOTE: Expand to handle more types if needed (e.g., strings via bytearray).